server:
  port: 8020

spring:
  application.name: betterreads
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.03d97e2ed5a941de
            client-secret: a497768dd6e8fa89e2d83fc704db47aae5ae39e2
  data:
    cassandra:
      keyspace-name: main
      username: oGZYZakZPsHLpjJCZkUziHSa
      password: BzwT8kOTz2_xb.5HyXhf7UvQsy,xfzLnmDR_EFD_bNodGlUF-qFXA0eeGJ1J0KIv0Ebw.4b0Q51i-ZPlRfFdGwRF+fnDOp-NCCy-x_T85o3ZkGnLA2aSCf9Psdjy4TTl
      schema-action: create-if-not-exists
      request:
        timeout: 30s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra:
    secure-connect-bundle: secure-connect.zip

astra.db:
    id: 00058f17-ba39-4b98-8337-8acca5496326-1
    region: us-west1
    keyspace: main
    application.token: AstraCS:oGZYZakZPsHLpjJCZkUziHSa:3a1008165bc155f25b29b5b0bce25034cc15d8e7f1c7c4bc7392b00cdee8e388  
