server:
  port: 8020

spring:
  application.name: betterreads
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 
            client-secret: 
  data:
    cassandra:
      keyspace-name: main
      username: oGZYZakZPsHLpjJCZkUziHSa
      password: 
      schema-action: create-if-not-exists
      request:
        timeout: 30s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra:
    secure-connect-bundle: secure-connect.zip

astra.db:
    id: 00058f17-ba39-4b98-8337-8acca5496326-1
    region: us-west1
    keyspace: main
    application.token: AstraCS:oGZYZakZPsHLpjJCZkUziHSa:3a1008165bc155f25b29b5b0bce25034cc15d8e7f1c7c4bc7392b00cdee8e388  
